# fly.toml app configuration file generated for summer-glitter-2194 on 2023-11-04T01:10:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "summer-glitter-2194"
primary_region = "atl"

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
